export const StringConstants ={

    //welcome screen

    WELCOME_TO_KINDRA :'Welcome to Kindra! ',
    WELCOME_TO :'Welcome to ',
    KINDRA:'Kindra!',
    WELCOME: 'Welcome!',
    SIGNUP:'Signup',

    //login Screen
    WELCOME_BACK :'Welcome Back!',
    PLEASE_LOGIN :'Please Login',
    PLEASE_CREATE_ACCOUNT: 'Please create a new account',
    DRIVER_NAME: 'Driver Name',

   //jobdetails screen
    CANCEL: 'Cancel',
    SEARCHING_DRIVER_NEAR_BY: 'Searching driver near by..',
    DOCUMENTS: 'Documents',
    DOCUMENT:'Document',
    HIRE: 'Hire',
    ACCEPT: 'Accept',
    REJECT: 'Reject',
    TOTAL_AMOUNT: 'Total Amount',
    TYPE_A_MESSAGE: 'Type message',

    //homescreen 
    VIEW_DETAIL: 'View Detail',
    ARRIVED_AT:'Arrived at',
    FILTER: 'Filter',
    SEARCH: 'Search',
    SELECT:'Select',

   //sign up
    SELECT_DOB: 'Select DOB',
    SELECT_GENDER: 'Select Gender',
    FULL_NAME: 'Full Name',
    EMAIL:'Email',
    PASSWORD:'Password',
    CONFIRM_PASSWORD:'Confirm Password',
    FORGOT_PASSWORD:'Forgot Password?',
    FORGET_PASSWORD: 'Forgot Password',
    LOGIN:'Login',
    IF_YOU_DONT_HAVE_ACCOUNT: "If you don't have an Account? ",
    I_HAVE_READ_AND_AGREE: 'I have read and agree to the ',
    SIGN_UP_NOW:'Sign up Now', 
    LOGIN_NOW:'Login Now', 
    BACK_TO_LOGIN: 'Back to Login?',
    USERNAME: 'User name',
    PHONE_NO: 'Phone Number',
    SUBMIT: 'Submit',
    ALREADY_HAVE_ACCOUNT: 'Already have an Account?',
    BACK_TO: 'Back to ',
    VERIFY: 'Verify',
    DID_NOT_RECEIVE_CODE: 'Didn’t received code?',
    RESEND: 'Re-send',
    UPLOAD_DRIVING_LICENCE: 'Upload Driving Licence',
    UPLOAD_INSURANCE_CERTIFICATE: 'Upload Insurance Certificate',
    FRONT_DRIVING_LICENCE: 'Front Driving Licence',
    BACK_DRIVING_LICENCE: 'Back Driving Licence',
    UPLOAD_IMAGE: 'Upload Image',
    UPLOADED: 'Uploaded',
    NO_SAVED_CONTACTS: 'No saved contacts',

    //create job new changes UI
    NEW_JOB: 'New Job',
    PICKUP_INFORMATION: 'Pickup Information',
    DROP_OFF_INFORMATION: 'Drop Off Information',
    DRIVER_PICKUP_INFORMATION: 'Driver Pickup Information',
    DRIVER_DROP_OFF_INFORMATION: 'Driver Drop Off Information',
    USER_PICKUP_INFORMATION: 'User Pickup Information',
    USER_DROP_OFF_INFORMATION: 'User Drop Off Information',
    CAN_COLLECT_NEAR: 'Can collect near',
    DRIVER_RETURNING_TO: 'Driver returning to',
    DATE_AND_TIME_SLOT: 'Date & Time Slot',
    VEHICLES: 'Vehicles',
    SELECT_WEIGHT: 'Select Weight',
    UPLOAD_DOCUMENTS: 'Upload Documents',
    ADD_MORE_PICKUP_LOCATION: 'Add Pickup Location',
    ADD_MORE_DROP_OFF_LOCATION: 'Add Drop Off Location',
    ADD_YOUR_NOTES: 'Add your notes...',
    TIME_SLOT: 'Time Slot',

       //create job
    MY_JOBS: 'My Jobs',
    ASSIGNED: 'Assigned',
    UNASSIGNED: 'UnAssigned', 
    TODAYS_JOB: 'Today’s job',
    UPCOMING_JOBS: 'Upcoming Jobs',
    PAST_JOBS: 'Past Jobs',
    NEW_LOADS: 'New Loads',
    YOU_HAVE_NO_JOB_TEXT: 'You don’t have any job press button and create new job.',
    CREATE_NEW_JOB: 'Create new job',
    AVAILABLE_FROM: 'Available from:',
    JOB_DETAIL: 'Job Detail',
    DETAIL: 'Detail',
    DRIVER_DETAIL: 'Driver Detail',
    VEHICLE: 'Vehicle',
    PHONE_NUMBER: 'Phone number',
    DATE: 'Date',
    DELIVERY_DATE:'Delivery Date',
    ITEM: 'Item',
    ITEMS: 'Items',
    PRICE: 'Price',
    TIME: 'Time',
    ADDITIONAL_AMOUNT: 'Additional Amount',
    LOCATIONS: 'Locations',
    ADDRESS: 'Address',
    ITEM_WEIGHT: 'Item (Weight)',
    ADDRESS2: 'Address:',
    ADDRESS_LINE_1: 'Address Line 1',
    ADDRESS_LINE_2: 'Address Line 2',
    MY_PROFILE: 'My Profile',
    CITY: 'City',
    STATE: 'State',
    ZIP_CODE: 'Zip code',
    DROP_PIN: 'Drop Pin',
    EDIT_PROFILE: 'Edit Profile',
    SAVED_CONTACTS: 'Saved Contacts',
    SAVED_CONTACT: 'Saved Contact',
    ADD_CONTACT: 'Add Contact',
    OTHER:'Other',

    ABOUT_US: 'About Us',
    TERMS_AND_CONDITIONS: 'Terms & Conditions',
    PRIVACY_POLICY: 'Privacy Policy',
    CONTACT_ADMIN: 'Contact Admin',
    DELETE_ACCOUNT: 'Delete Account',
    LOGOUT: 'Logout',
    NOTIFICATIN: 'Notification',
    UPDATE: 'Update',
    NEW_CONTACT: 'New Contact',
    SAVE: 'Save',
    SELECT_LOCATION: 'Select Location',
    ENTER_CONTACT_NAME: 'Enter Contact Name',
    DID_NOT_FIND_ADDRESS: 'Didn’t Find Address?',
    CHOOSE_CONTACT: 'Choose Contact',
    TYPE_MESSAGE: 'Type message..',
    TITLE: 'Title',
    PLEASE_ENTER_TITLE: 'Please enter title',
    PLEASE_ENTER_A_VALID_TITLE: 'Please enter a valid title, only alphabets are allowed in title',
    TITLE_SHOULD_BE_ATLEAST_3_CHARACTERS_LONG: 'Title should be atleast 3 characters long',
    PLEASE_ENTER_MESSAGE:'Please enter your message',
    DESCRIPTION_SHOULD_BE_ATLEAST_3_CHARACTERS_LONG: 'Message should be atleast 3 characters long',
    PLEASE_ENTER_A_VALID_DESCRIPTION: 'Please enter a valid message, only aplhabets are allowed in message field',
    SEND: 'Send',
    ITEM_DETAILS: 'Item Details',
    PICKUP: 'Pickup',
    DROP_OFF: 'Drop-off',
    NOTE: 'Note',
    ADD_NEW_ADDRESS: 'Add new address',
    SELECT_DATE: 'Select Date',
    SELECT_VEHICLE: 'Select Vehicle',
    ENTER_WEIGHT: 'Enter Weight',
    WEIGHT: 'Weight',
    CONTACT_NUMBER: 'Contact number',
    ENTER_CONTACT_NUMBER: 'Enter contact number',
    ADD_NUMBER: 'Add Number',
    NOTES: 'Notes',
    BILL_NOTES: 'Bill Notes',
    NOTES2: 'Notes..',
    YES: 'Yes',
    NO: 'No', 
    ALERT: 'Alert',
    DELETE_ACCOUNT_WARNING: 'Do you want to delete this account?',
    LOGOUT_WARNING: 'Are you sure you want to logout?',
    DELETE_CONTACT_WARNING: 'Do you want to delete contact?',
    VERIFY_YOUR_EMAIL_ADDRESS: 'Verify Your Email Address',
    EMAIL_VERIFY_MESSAGE: 'Please enter the OTP sent to your registered email Id to continue to login',
    //  EMAIL_VERIFY_MESSAGE: 'Please click the button below to verify your email address and activate your account.',
     VERIFY_STATEMENT: 'Please enter the verification code that we have send to your registered Email Id',
     REVIEW_AND_RATING: 'Review & Rating!',
     REVIEW_AND_RATING2: 'Review & Rating',
     COMMENT_HERE: 'Comment here..',
     EDIT_CONTACT: 'Edit Contact',
     SELECT_DELIVERY_TIME_SLOT: 'Select Delivery Time Slot',
     END_TIME: 'End Time', 
     START_TIME: 'Start Time', 
     SELECT_TIME: 'Select Time',
     SELECT_PICKUP_TIME: 'Select Pickup Time',
     START_DATE: 'Start Date',
     END_DATE: 'End Date',
     ITEM_COUNT: 'Item Count',
     UPLOAD_DOCUMENT: 'Upload Document',
     CREATE_JOB: 'Create Job',
     CLICK_TO_UPLOAD: 'Click to Upload',
     COMPANY_NUMBER: 'Company Number',
     OK: 'OK',
     ROUTE_STATUS: 'Route Status',
     COLLECTED: 'Collected',
     COMPLETED_JOB: 'Completed Job',
     CANCELLED_JOB: "Cancelled Job",
     YOU_DONT_HAVE_NOTIFICATION: `You don't have any notifications yet`,
     CLEAR: 'Clear',
     WOULD_YOU_WANT_TO_CANCEL: 'Would you want to cancel? ',
     REASON_FOR_CANCELLATION: 'Reason for cancellation',
     TYPE_REASONS: 'Type reasons',
     CANCEL_JOB: 'Cancel Job',
     VERIFICATION: 'Verification',
     COMPLETED: 'Completed',
     READ: 'Read',
     DELETE: 'Delete',
     CANCELLED: 'Cancelled',
     PROFILE_UPDATED_SUCCESSFULLY: 'Profile updated sucessfully',
     BILL_CREATED_SUCCESSFULLY: 'Bill created successfully',
     JOB_FINISHED_SUCCESSFULLY: 'Job finished successfully',
     JOB_REQUEST_ACCEPT_SUCCESSFULLY: 'Job request accepted successfully',
     HOTSHOT_PROPOSAL_ACCEPTED_SUCCESSFULLY: 'Hotshot proposal accepted successfully',
     COMPLETED_HOTSHOT: 'Completed Hotshot',

     ON_ROUTE: "On Route",
     ARRIVED: 'Arrived',
     START_JOB: 'Start Job',
     DELIEVERED: 'Delivered',
     NEW_HOTSHOTS: 'New Hotshots',
     PAST_HOTSHOTS: 'Past Hotshots',
     PROPOSAL: 'Proposal',
     VIEW_PROPOSALS: 'View Proposals',

     //contact_screen
     DONE:'Done',
     CONTACT_ADDED_SUCCESSFULLY:'Contact added successfully',
     CONTACT_UPDATED_SUCCESSFULLY:'Contact updated successfully',
     LOGOUT_SUCCESS: 'Logout Success',
     CONTACT_DELETED_SUCCESSFULLY: 'Contact deleted successfully',
     //validation msgs
     PLEASE_ENTER_YOUR_FULLNAME: 'Please enter your full name',
     PLEASE_ENTER_YOUR_EMAIL_ID: 'Please enter your email ID',
     PLEASE_ENTER_YOUR_CORRECT_USERNAME: 'Please enter the correct name, only alphabets are allowed in full name', 
     PLEASE_ENTER_YOUR_CORRECT_FULL_NAME: 'Please enter your correct full name',

     PLEASE_ENTER_A_VALID_EMAIL_ID: 'Please enter a valid email ID',
     PLEASE_ENTER_YOUR_PASSWORD: 'Please enter your password',
     PLEASE_CONFIRM_YOUR_PASSWORD: 'Please confirm your password',
     EMOJI_NOT_ALLOWED_IN_PASSWORD: 'Emoji does not allowed in password field',

    PASSWORD_VALIDATION: 'Password must have minimum 8 characters,\nOne uppercase letter,\nOne lowercase letter,\nOne number, and\nOne special character',
     PASSWORD_DOES_NOT_MATCH: 'Password does not match',
     PLEASE_UPLOAD_YOUR_DRIVING_LICENCE_FRONT_PAGE: 'Please upload the front image of your driving licence',
     PLEASE_UPLOAD_YOUR_DRIVING_LICENCE_BACK_PAGE: 'Please upload the back image of your driving licence',
     PLEASE_UPLOAD_INSURANCE_CERTIFICATE: 'Please upload your Insurance Certificate',
     PLEASE_UPLOAD_FIRST_INSURANCE_CERTIFICATE: 'Please upload your first insurance certificate',
     PLEASE_UPLOAD_SECOND_INSURANCE_CERTIFICATE: 'Please upload your second insurance certificate',
     PLEASE_UPLOAD_THIRD_INSURANCE_CERTIFICATE: 'Please upload your third insurance certificate',

     PLEASE_ENTER_YOUR_USERNAME: 'Please enter your username',
     PLEASE_ENTER_YOUR_PHONE_NUMBER: 'Please enter your Phone Number',
     PLEASE_ENTER_YOUR_COMPANY_NUMBER: 'Please enter your Company Number',
     PLEASE_ENTER_YOUR_CORRECT_PHONE_NUMBER: 'Please enter your correct Phone Number',
     PLEASE_ENTER_YOUR_ADDRESS_LINE_1: 'Please enter your Address line 1',
     PLEASE_ENTER_YOUR_CORRECT_ADDRESS_LINE_1: 'Please enter your correct Address line 1',
     PLEASE_ENTER_YOUR_ADDRESS_LINE_2: 'Please enter your Address line 2',
     PLEASE_ENTER_YOUR_CORRECT_ADDRESS_LINE_2: 'Please enter your correct Address line 2',
     PLEASE_ENTER_YOUR_CITY: 'Please enter your City',
     PLEASE_ENTER_YOUR_CORRECT_CITY: 'Please enter your correct city',
     PLEASE_ENTER_YOUR_CORRECT_CITY_REGEX: 'Please enter the correct city, only alphabets are allowed in city',
     PLEASE_ENTER_YOUR_STATE: 'Please enter your State',
     PLEASE_ENTER_YOUR_CORRECT_STATE: 'Please enter your correct state',
     PLEASE_ENTER_YOUR_CORRECT_STATE_REGEX: 'Please enter the correct state, only alphabets are allowed in state',
     PLEASE_ENTER_YOUR_ZIP_CODE: 'Please enter your Zip Code',
     PLEASE_ENTER_YOUR_CORRECT_ZIP_CODE: 'Please enter the correct zip code',
     PLEASE_ENTER_YOUR_CONTACT_NAME: 'Please enter your contact name',
     PLEASE_SELECT_THE_LOCATION: 'Please select the location',
     PLEASE_SELECT_YOUR_GENDER: 'Please select your gender',
     PLEASE_ENTER_YOUR_DOB: 'Please enter your date of birth',
     AGE_MUST_BE_GREATER_THAN_18: 'Age must be greater than 18',
     PLEASE_UPLOAD_THE_DOCUMENT: 'Please upload the document',
     PLEASE_ACCEPT_OUR_TERMS: 'Please accept the terms and conditions to proceed',
     PLEASE_ACCEPT_ALL_THE_TERMS: 'Please accept all the terms and conditions to proceed further',
     PLEASE_ADD_INSTRUCTIONS_MESSAGE: 'Please add instructions for the driver',
     PLEASE_SELECT_THE_TIME_FOR_PICKUP: 'Please select the time for pickup',
     PLEASE_ENTER_PRICE: 'Please enter the price',
     PLEASE_ENTER_VALID_PRICE: 'Please enter a valid format for price',

     //driver home
     NO_JOBS_AVAILABLE_LINE: `You don't have any job press refresh button and check after few minutes.`,
     JOB_REQUEST: 'Job Request',
     IN_JOBS: 'In Jobs',
     OUT_JOBS: 'Out Jobs',
     REFRESH: 'Refresh',
     NO_HOTSHOT: `You don't have any Hotshot, Press below button and create new Hotshot.`,
     ADD_HOTSHOT: 'Add Hotshot',
     HOTSHOT: 'Hotshot',
     CREATE_HOTSHOT: 'Create Hotshot',
     ENTER_PRICE: 'Enter Price',
     CREATE_NEW_HOTSHOT: 'Create new Hotshot',
     ADD_SIGNATURE: 'Add Signature',
     CUSTOMER_SIGNATURE: 'Customer Signature',
     MAKE_FINAL_BILL: 'Make Final Bill',
     AMOUNT: 'Amount',
     WANT_ADDITIONAL_AMOUNT: 'Request additional amount',
   //   WANT_ADDITIONAL_AMOUNT: 'Do you want some additional amount?',
     ENTER_AMOUNT: 'Enter Amount',
     ADD_NOTE: 'Add Note',
     FINISH_JOB: 'Finish Job',
     LIKE_TO_CREATE_HOTSHOT: 'Would you like to create a hotshot load? Back to your location.',
     PLEASE_CHECK_YOUR_INTERNET_CONNECTION: 'Please check your internet connection',
     CITY_SHOULD_BE_ATLEAST_3_CHARACTERS_LONG: 'City should be atleast 3 characters long',
     STATE_SHOULD_BE_ATLEAST_3_CHARACTERS_LONG: 'State should be atleast 3 characters long',
     JOB_CREATED_SUCCESSFULLY: 'Job created sucessfully',
     HOTSHOT_CREATED_SUCCESSFULLY: 'Hotshot created sucessfully',
     HOTSHOT_CANCELLED_SUCCESSFULLY: 'Hotshot cancelled successfully',
     HOTSHOT_FINISHED_SUCCESSFULLY: 'Hotshot finished successfully',
     CANCEL_HOTSHOT_WARNING: 'Are you sure you want to cancel this hotshot?',
     TAP_TO_VIEW_THE_DOCUMENT: 'Tap to view the document',
     //change password validation
     CHANGE_PASSWORD: 'Change Password',
     ENTER_EMAIL: 'Enter Email',
     ENTER_NEW_PASSWORD: 'Enter new password',
     CONFIRM_NEW_PASSWORD: 'Confirm new password',
     THE_ENTERED_EMAIL_ID_IS_INCORRECT: 'The entered Email Id is incorrect',
     PLEASE_ENTER_YOUR_NEW_PASSWORD:'Please enter your new password',
     MESSAGE_SENT_SUCCESSFULLY: "Message sent sucessfully",
     ENTER_OLD_PASSWORD: 'Enter old password',
     PLEASE_ENTER_YOUR_OLD_PASSWORD: 'Please enter your old password',

     CONTACT_NAME_SHOULD_BE_ATLEAST_3_CHARACTERS_LONG: 'Contact name should be atleast 3 characters long',
     PLEASE_ENTER_YOUR_CORRECT_CONTACT_NAME: 'Please enter the correct contact name, only alphabets are allowed in name',
     EMOJI_NOT_ALLOWED_IN_ADDRESS: 'Emoji is not allowed in address field',
     PLEASE_SELECT_THE_LOCATION_ON_MAP_USING_DROP_PIN: 'Please select the location on map using Drop Pin',
     PLEASE_ENTER_REASON: 'Please enter the reason for cancel job',
     JOB_CANCELLED_SUCCESSFULLY: 'Job cancelled successfully',
     EMOJI_IS_NOT_ALLOWED_IN_THIS_FIELD: 'Emoji is not allowed in this field',
     PLEASE_ENTER_AMOUNT: 'Please enter the amount',
     PLEASE_ENTER_ADDITIONAL_AMOUNT: 'Please enter the additional amount',
     PLEASE_ENTER_VALID_AMOUNT: 'Please enter a valid amount',
     PLEASE_ENTER_VALID_ADDITIONAL_AMOUNT: 'Please enter a valid additional amount',
     TAP_TO_VIEW_DOCUMENT: 'Tap to view the document',
     VIEW_SIGNATURE: 'View Signature',
     //create job validations
     EMOJI_IS_NOT_ALLOWED_IN_NOTES: 'Emoji is not allowed in notes',
     PLEASE_SELECT_THE_DELIEVERY_DATE: 'Please select the delievery date',
     PLEASE_SELECT_THE_SLOT_FOR_DELIEVERY: 'Please select the slot for delievery',
     PLEASE_SELECT_THE_START_TIME_FOR_DELIEVERY: 'Please select the start time for delievery',
     PLEASE_SELECT_THE_END_TIME_FOR_DELIEVERY: 'Please select the end time for delievery',
     PLEASE_SELECT_THE_TIME_FOR_DELIEVERY: 'Please select the time for delievery',
     PLEASE_SELECT_THE_VEHICLE: 'Please select the vehicle',
     PLEASE_ENTER_THE_WEIGHT: 'Please enter the weight',
     PLEASE_ENTER_VALID_FORMAT: 'Please enter the valid format for weight',
     WEIGHT_MUST_NOT_BE_ZERO: 'Weight must not be zero',
     EMOJI_IS_NOT_ALLOWED_IN_WEIGHT: 'Emoji is not allowed in weight',
     PLEASE_ENTER_THE_CONTACT_NUMBER: 'Please enter the contact number',
     PLEASE_ENTER_THE_CORRECT_CONTACT_NUMBER: 'Please enter your correct contact number',
     PLEASE_WRITE_ANY_NOTE: 'Please write any note',
     PLEASE_UPLOAD_FIRST_DOCUMENT: 'Please upload your first document',
     PLEASE_UPLOAD_SECOND_DOCUMENT: 'Please upload your second document',
     PLEASE_UPLOAD_THIRD_DOCUMENT: 'Please upload your third document',
     PLEASE_UPLOAD_FOURTH_DOCUMENT: 'Please upload your fourth document',
     PLEASE_UPLOAD_FIFTH_DOCUMENT: 'Please upload your fifth document',
     PLEASE_SELECT_ANY_OTHER_LOCATION: "Please select any other location as we do not find the specific path between these locations",
     PLEASE_ENTER_THE_PICKUP_ITEMS_WEIGHT: 'Please enter the Pickup Items weight',
     PICKUP_ITEMS_WEIGHT_MUST_NOT_BE_ZERO: 'Pickup Items Weight must not be zero',
     PICKUP_CITY_SHOULD_BE_ATLEAST_3_CHARACTERS_LONG: 'Pickup City should be atleast 3 characters long',
     PICKUP_STATE_SHOULD_BE_ATLEAST_3_CHARACTERS_LONG: 'Pickup State should be atleast 3 characters long',
     DROP_OFF_CITY_SHOULD_BE_ATLEAST_3_CHARACTERS_LONG: 'Drop off City should be atleast 3 characters long',
     DROP_OFF_STATE_SHOULD_BE_ATLEAST_3_CHARACTERS_LONG: 'Drop off State should be atleast 3 characters long',
     PLEASE_ENTER_YOUR_CORRECT_PICKUP_ZIP_CODE: 'Please enter the correct Pickup zip code',
     PLEASE_ENTER_YOUR_CORRECT_DROP_OFF_ZIP_CODE: 'Please enter the correct Drop Off zip code',
     PLEASE_ENTER_VALID_FORMAT_PICKUP: 'Please enter the valid format for weight for PickUp Items',
     EMOJI_IS_NOT_ALLOWED_IN_PICKUP_ITEM_WEIGHT: 'Emoji is not allowed in Pickup item weight',
     PLEASE_SELECT_THE_PICKUP_LOCATION: 'Please select the Pickup location',
     PLEASE_SELECT_THE_DROP_OFF_LOCATION: 'Please select the Drop Off location',
     PLEASE_SELECT_THE_PICKUP_LOCATION_ON_MAP_USING_DROP_PIN: 'Please select the Pickup location on map using Drop Pin',
     PLEASE_SELECT_THE_DROP_OFF_LOCATION_ON_MAP_USING_DROP_PIN: 'Please select the Drop Off location on map using Drop Pin',
     PLEASE_ENTER_YOUR_PICKUP_ADDRESS_LINE_1: 'Please enter your Pickup Address line 1',
     PLEASE_ENTER_YOUR_DROP_OFF_ADDRESS_LINE_1: 'Please enter your Drop Off Address line 1',
     PLEASE_ENTER_YOUR_PICKUP_ADDRESS_LINE_2: 'Please enter your Pickup Address line 2',
     PLEASE_ENTER_YOUR_DROP_OFF_ADDRESS_LINE_2: 'Please enter your Drop Off Address line 2',
     PLEASE_ENTER_YOUR_PICKUP_CITY: 'Please enter your Pickup City',
     PLEASE_ENTER_YOUR_DROP_OFF_CITY: 'Please enter your Drop Off City',
     PLEASE_ENTER_YOUR_PICKUP_STATE: 'Please enter your Pickup State',
     PLEASE_ENTER_YOUR_DROP_OFF_STATE: 'Please enter your Drop Off State',
     PLEASE_ENTER_YOUR_CORRECT_PICKUP_STATE_REGEX: 'Please enter the correct Pickup state, only alphabets are allowed in state',
     PLEASE_ENTER_YOUR_CORRECT_DROP_OFF_STATE_REGEX: 'Please enter the correct Drop Off state, only alphabets are allowed in state',
     PLEASE_ENTER_YOUR_PICKUP_ZIP_CODE: 'Please enter your Pickup Zip Code',
     PLEASE_ENTER_YOUR_DROP_OFF_ZIP_CODE: 'Please enter your Drop Off Zip Code',
     PLEASE_ENTER_YOUR_CORRECT_PICKUP_CITY_REGEX: 'Please enter the correct Pickup city, only alphabets are allowed in city',
     PLEASE_ENTER_YOUR_CORRECT_DROP_OFF_CITY_REGEX: 'Please enter the correct Drop Off city, only alphabets are allowed in city',


     PLEASE_SELECT_PICKUP_ITEM: "Please select the pickup item",
     PLEASE_ENTER_PICKUP_ITEM_COUNT: 'Please enter the pickup item count',
     PICKUP_CANNOT_ZERO: `Pickup item count can't be zero`,
     PLEASE_ENTER_CORRECT_PICKUP_ITEM_COUNT: 'Please enter the correct pickup item count, only integer number are allowed in Item Count',
     PLEASE_SELECT_DROP_OFF_ITEM: "Please select the drop off item",
     PLEASE_SELECT_ANOTHER_DROP_OFF_LOCATION: 'Please select another drop-off location',

     ADD_MORE_PICKUP_ITEM: 'Add Pickup Item',
     ADD_MORE_DROP_OFF_ITEM: 'Add Drop Off Item',}